username: yourusername
password: yourpasword
phone_number: yourphonenumebr

profile_path: "" #can be empty, will default to 'C:\Users\<user>\AppData\Local\Google\Chrome\User Data\Default'

positions:
  - Full stack Engineer
  - AI/ML Engineer
  - AI Developer
  - Software Engineer

locations:
  - United Kingdom
  - Remote

salary: 60,000
rate: 35
# --------- Optional Parameters -------
uploads:
  Resume: "./cv1.pdf"
  Cover Letter: "./cl.pdf"
  #Photo: # PATH TO photo

output_filename:
  - "./out.csv"

# blacklist:
# - # Company names you want to ignore

experience_level:
  - 1 # Entry level
  - 2 # Associate
  - 3 # Mid-Senior level
  # - 4 # Director
  # - 5 # Executive
  # - 6 # Internship
